### ISSUE TITLE
ModuleNotFoundError: no module named "alpaca"

### ISSUE THREAD

**Issue by Lunarien** [Finned-Digital-Solutions/hft-ext#1]
![image](https://user-images.githubusercontent.com/73956350/219140686-7b4280cf-a7a9-47ed-8e1f-eab7021ef962.png)
I did the instructions from the readme file, yet I still receive this error. I do have alpaca installed though.

Is this issue on my side or is this not my fault?

**Comment by flancast90** [comment]
Hey @Lunarien ,
It could be an issue with me autogenerating the ``requirements.txt`` file. Try running ``py -m pip install alpaca`` and then running ``python main.py`` and see if it works.

**Comment by Lunarien** [comment]
I do have it installed. Just checked with your provided command:
![image](https://user-images.githubusercontent.com/73956350/219280487-01f61a5d-c51f-4863-bba6-698f29191ecc.png)

**Comment by Lunarien** [comment]
so I noticed alpaca in the site-packages does not have the name "alpaca":
![image](https://user-images.githubusercontent.com/73956350/219282828-74c77188-6581-43ef-8c6d-f465d64585aa.png)
is this the problem?

**Comment by Lunarien** [comment]
So perhaps the problem is that "alpaca" is not a folder in the site-packages folder..
![image](https://user-images.githubusercontent.com/73956350/219283636-e57360c4-ec0f-4adc-92d1-e9b2d84d418c.png)
Could this be the problem?

**Comment by Lunarien** [comment]
I think I have found the problem. I don't think the module is the correct alpaca:
![image](https://user-images.githubusercontent.com/73956350/219352990-86bfee9f-c865-4957-8e2c-13c00819ebd9.png)
If you go to the site (https://github.com/activesys/alpaca-llama), the text is in Chinese.

**Comment by flancast90** [comment]
Weird, thanks for investigating. I thought the package name was Alpaca, but let me check again.

**Comment by flancast90** [comment]
Well I'm officially an idiot - the official package name is `alpaca-py`.

`py -m pip install alpaca-py` and let me know how it goes.

**Comment by flancast90** [comment]
Also updated the `requirements.txt` to use the updated package name. If everything works ok for you, I'll close this as fixed.

**Comment by Lunarien** [comment]
The program is opening fine now. You can close this issue.
